# Generated by Django 5.0.1 on 2024-02-16 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Servicecentername1', models.CharField(max_length=20)),
                ('Email1', models.EmailField(max_length=254)),
                ('Phonenumber1', models.IntegerField()),
                ('Password1', models.CharField(max_length=20)),
                ('Address1', models.CharField(max_length=200)),
                ('servicecenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
