# Generated by Django 5.0.1 on 2024-02-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_service_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='service_center',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
