# Generated by Django 5.0.1 on 2024-02-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customer_status_service_center_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solar_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productname', models.CharField(max_length=20)),
                ('Image1', models.ImageField(null=True, upload_to='Image')),
                ('Price', models.IntegerField()),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
    ]
