# Generated by Django 5.0.1 on 2024-02-16 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='solar_products',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customer'),
        ),
    ]
