# Generated by Django 5.0.2 on 2024-02-17 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='solarproducts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.solar_products'),
        ),
    ]
