# Generated by Django 5.0.2 on 2024-02-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_booking_solarproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Message2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
