# Generated by Django 5.0.2 on 2024-02-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_booking_message2'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Productname1',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
