# Generated by Django 5.0.2 on 2024-02-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='solar_products',
            name='Stock',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
