# Generated by Django 5.0.2 on 2024-02-17 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='solarproducts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.solar_products'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
