# Generated by Django 5.0.2 on 2024-02-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AddField(
            model_name='cart',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Amount',
            field=models.IntegerField(null=True),
        ),
    ]
