# Generated by Django 5.0.2 on 2024-02-17 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_order_total_price_cart_amount_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.order'),
        ),
    ]
