# Generated by Django 5.0.2 on 2024-02-17 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_cart_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Amount',
        ),
    ]
