# Generated by Django 5.0.2 on 2024-02-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_cart_amount_remove_cart_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='amt',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(default='pending', max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
