# Generated by Django 5.0.2 on 2024-02-19 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_cart_amt_cart_qty_cart_status_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_center',
            name='Price1',
            field=models.IntegerField(null=True),
        ),
    ]
