# Generated by Django 5.0.2 on 2024-02-19 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_service_center_price1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_center',
            name='Price1',
        ),
    ]
