# Generated by Django 5.0.2 on 2024-02-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_service_center_price1'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Price1',
            field=models.IntegerField(null=True),
        ),
    ]
