# Generated by Django 5.0.2 on 2024-02-19 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_booking_price1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Price1',
        ),
    ]
