# Generated by Django 5.0.2 on 2024-02-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_booking_price1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Price1',
        ),
        migrations.AddField(
            model_name='service_center',
            name='Price1',
            field=models.IntegerField(null=True),
        ),
    ]
