# Generated by Django 5.0.2 on 2024-02-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_booking_price1_service_center_price1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_center',
            name='Phonenumber1',
            field=models.IntegerField(null=True),
        ),
    ]
