# Generated by Django 5.0.2 on 2024-02-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='Price2',
            field=models.IntegerField(null=True),
        ),
    ]
